
// Allow only below samplers.
SamplerState StaticPointWrapSampler;
SamplerState StaticPointClampSampler;
SamplerState StaticLinearWrapSampler;
SamplerState StaticLinearClampSampler;
SamplerState StaticAnisotropicWrapSampler;
SamplerState StaticAnisotropicClampSampler;